import mongoose from "mongoose";

import PostMessage_Model from "../models/post_models.js";


export const getPost = async (req, res) => {

    try {

        ///try to get all post by the mogoose with find
        const postMessages = await PostMessage_Model.find();

        res.status(200).json(postMessages);

    } catch (error) {

        res.status(404).json({ message: error.message });
    }
}

export const newPost = async (req, res) => {

    //this is get from the front-end
    const post = req.body;

    //model
    const newPost = new PostMessage_Model(post);

    try {

        ///we can do that because the name of the collection is already define in the mogoose model
        await newPost.save();

        res.status(201).json(newPost);

    } catch (error) {
        res.status(409).json({ message: error.message });
    }
}

export const updatePost = async (req, res) => {

    // const post_id = req.params.id;
    ///get the param id in the req.params and rename it to _id
    const { id: _id } = req.params;

    //this is get from the front-end , methode post
    const post = req.body;

    ///check if this id is generated by the mongoose.
    if (!mongoose.Types.ObjectId.isValid(_id))
        return res.status(404).send("No post with that id !!!")

    const updatedPost = await PostMessage_Model.findByIdAndUpdate(_id, post, { new: true });

    res.json(updatedPost);
}

export const deletePost = async (req, res) => {

    const { id: _id } = req.params;

    if (!mongoose.Types.ObjectId.isValid(_id))
        return res.status(404).send('No post with that id !!!')

    await PostMessage_Model.findByIdAndRemove(_id);

    res.json({ message: "Post deleted successfully" });
}

export const likePost = async (req, res) => {

    const { id } = req.params;

    const post = await PostMessage_Model.findById(id);
    const update_like_post = await PostMessage_Model.findByIdAndUpdate(id, { likeCount: post.likeCount + 1 }, { new: true })

    res.json(update_like_post);
}